name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix build '.?submodules=1#squirrel'
    - uses: actions/upload-artifact@v4
      with:
        name: libsquirrel.a
        path: result/lib/libsquirrel.a

